apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vsphere-retain
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-balanced
  fstype: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
